config/routes.rb
Rails.application.routes.draw do
  root :to => 'users#index'
  get '/log-in' => 'sessions#new'
  post '/log-in' => 'sessions#create'
  get '/log-out' => 'sessions#destroy', as: :log_out

  resources :users

  resources :questions do
    resources :comments
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :comment_content
  belongs_to :question
  belongs_to :user


end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :votes
  
  validates_presence_of :question_title
  validates_presence_of :question_content
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :comments
  has_many :votes
  validates_presence_of :user_name
  validates_presence_of :email

  attr_accessor :password
  validates_confirmation_of :password
  before_create :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

end

app/models/votes.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def logged_in?
    if session[:user_id]
      true
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @question = Question.find(params[:question_id])
    @comment = Comment.new
  end

  def create
    @question = Question.find(params[:question_id])
    @comment = current_user.comments.new(comment_params)
    @comment.question_id = params[:question_id]
    if @comment.save
      UserMailer.response_confirmation(current_user).deliver
      flash[:notice] = "Thanks for posting your comment!"
      redirect_to question_path(@comment.question_id)
    else
      flash[:alert] = "There was an error, try again please"
      redirect_to :back
    end
  end

  def edit
    @question = Question.find(params[:question_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @question = Question.find(params[:question_id])
    @comment = Comment.find(params[:id])
    @question.comments(:first_response => true).any?
    @question.comments.update_all(:first_response => false)
    @comment.update(:first_response => true)
    flash[:notice] = "Got it! Saving your favorite response now!"
    redirect_to question_path(@comment.question_id)
  end

  def destroy
    @question = Question.find(params[:question_id])
    @comment = current_user.comments.find(params[:id])
    @comment.destroy
    flash[:alert] = "Comment destroyed!"
    redirect_to question_path(@question)
  end

private
  def comment_params
    params.require(:comment).permit(:comment_content)
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      flash[:notice] = "Thanks for asking! Please check back to see responces."
      redirect_to user_path(current_user)
    else
      flash[:alert] = "There was an error, try again please."
      redirect_to :back
    end
  end

  def show
    @question = Question.find(params[:id])
  end

  def edit
    @question = current_user.questions.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(params[:question])
      flash[:notice] = "Question successfully updated!"
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    if @question.destroy
      flash[:alert] = "Question successfully deleted!"
    end
    redirect_to user_path(current_user)
  end

private

  def question_params
    params.require(:question).permit(:question_title, :question_content)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && User.authenticate(params[:email], params[:password])
      flash[:notice] = "Successfully logged in"
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:error] = "User name or password entered incorrectly."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to "/"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @questions = Question.all
  end

  def show
    @user = User.find(params[:id])
    @questions = @user.questions
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.signup_confirmation(@user).deliver
      flash[:notice] = "Thanks for joining! An email has been sent to your account. Please log in."
      redirect_to '/log-in'
    else
      flash[:alert] = "There was an error, try again please."
      redirect_to :back
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(edit_params)
      flash[:notice]="You have successfully updated #{@user.user_name}!"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    UserMailer.delete_confirmation(@user).deliver
    @user.destroy
    session[:user_id] = nil
    flash[:alert] = "Account destroyed!"
    redirect_to "/"
  end



private
  def user_params
    params.require(:user).permit(:user_name, :email, :password, :password_confirmation)
  end

  def edit_params
    params.require(:user).permit(:user_name, :email)
  end


end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    @question = Question.find(params[:question_id])
    Vote.create({:user_id => current_user.id, :comment_id => params[:comment_id]})
    flash[:notice] = "Best answer accepted!"
    redirect_to question_path(@question)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<%= render 'shared/header', title: "New Response" %>

<%= bootstrap_form_for [@question, @comment] do |f| %>
<%=f.text_area :comment_content, placeholder: 'Give a Response', size: "50X12" %>
<%=f.submit "Give your feedback!" %>
<%end%>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
<% if msg.is_a?(String) %>
<div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
</div>
<% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <ul class="nav navbar-nav">

    <li><%= link_to 'Home', users_path %></li>
    <% if logged_in? %>
    <li><%= link_to 'Your Page', user_path(current_user) %></li>
    <li><%= link_to 'Account Settings', edit_user_path(current_user) %></li>
    <li><%= link_to 'Logout', log_out_path %></li>
    <% else %>
    <li><%= link_to "Login", log_in_path %></li>
    <li><%= link_to "Sign Up", new_user_path %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stack Overflow</title>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </div>

</body>
</html>

app/views/questions/edit.html.erb
<%= render 'shared/header', title: "Edit Question" %>

<%= bootstrap_form_for(@question) do |f| %>
<%=f.text_field :question_title, placeholder: 'New Title'  %>
<%=f.text_area :question_content, placeholder: 'New Content', size: "50X12" %>
<%=f.submit "Revise your question!" %>
<%end%>

app/views/questions/new.html.erb
<%= render 'shared/header', title: "New Question" %>

<%= bootstrap_form_for(@question) do |f| %>
<%=f.text_field :question_title, placeholder: 'Title'  %>
<%=f.text_area :question_content, placeholder: 'Content', size: "50X12" %>
<%=f.submit "Ask Away!" %>
<%end%>

app/views/questions/show.html.erb
<%= render 'shared/header', title: @question.question_title %>

<p class="q-content"><%= @question.question_content %></p>

<% if @question.comments.any? %>
  <h4>Responses</h4>

  <p><% @question.comments.order(first_response: :desc).each do |comment| %>
    <% if current_user && comment.first_response == false && current_user.id == @question.user_id  %>
      <%= link_to question_comment_path(@question, comment), :method => "Patch"  do %>
        <span class="glyphicon glyphicon-star-empty"></span>
      <% end %>
    <% elsif current_user && comment.first_response == true && current_user.id == @question.user_id  %>
        <span class="glyphicon glyphicon-star"></span>
    <% end %>

    <%= comment.comment_content %>

    <% if current_user.id == comment.user_id %>
    | <%= link_to "Delete", question_comment_path(@question, comment),
                            :data => {:confirm => "You sure?",
                                      :method => "delete"} %>

    <% end %>
  </p>

  <% end %>

<% else %>
  <br><h4>There are no comments. Click below to add a comment.</h4>
<% end %>

<%= link_to "Respond now!", new_question_comment_path(@question) %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/shared/_header.html.erb
<h1><%= 'Stack Overflow Clone' %> <%=" | #{title}"%></h1>

<%= render 'layouts/flash' %>

app/views/users/edit.html.erb
<%= render 'shared/header', title: "Edit Your Account" %>

<%= bootstrap_form_for(@user) do |f| %>
<%=f.text_field :email, placeholder: 'New E-mail' %>
<%=f.text_field :user_name, placeholder: 'New User Name'  %>
<%=f.submit "Edit" %>
<%end%>




  <%= link_to "Delete Account", user_path(@user),
  data: {confirm: "Are you sure?",
  method: :delete} %>

app/views/users/index.html.erb
<%= render 'shared/header', title: "Home" %>

<% if @questions.any? %>
<h2>All Posted Questions:</h2>

<ul>
  <% @questions.each do |question| %>
  <li> <h4><%= link_to question.question_title, question_path(question) %></h4>
      <ul>
        <li><%= question.question_content %></li>
      </ul>
  </li>
  <% end %>
</ul>

  <% else %>
  <br>

  <h4>There are no questions yet.</h4>
<% end %>

app/views/users/new.html.erb
<%= render 'shared/header', title: "Sign up" %>

<%= bootstrap_form_for(@user) do |f| %>
  <%=f.text_field :user_name, placeholder: 'User Name' %>
  <%=f.text_field :email, placeholder: 'E-mail'  %>
  <%=f.password_field :password, placeholder: 'Password'  %>
  <%=f.password_field :password_confirmation, placeholder: 'Retype Password'  %>
  <%=f.submit "Sign Up Now" %>
<%end%>

app/views/users/show.html.erb
<%= render 'shared/header', title: @user.user_name %>
<%= link_to "Have a Question?", new_question_path, class:"btn, btn-success" %>


<% if current_user.questions.any? %>
<h4>Your Questions:</h4>
<ul>
  <% current_user.questions.each do |question| %>
    <li>  <%= link_to question.question_title, question_path(question) %> : <%= question.created_at %> |
      <%= link_to "Edit", edit_question_path(question) %> |
      <%= link_to "Delete", question_path(question),
                            :data => {:confirm => "You sure?",
                                      :method => "delete"} %>
      <ul>
        <li> <%= question.question_content %></li>
      </ul>
    </li>
    <% end %>
</ul>
  <% else %>
  <br>
    <h4>
      Write your first question!
    </h4>
  <% end %>